version: '3.7'

services:
  web:
    container_name: djaman-web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php
      - db

  php:
    container_name: djaman-php
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_ERROR_REPORTING=E_ALL

  db:
    image: mysql:5.7
    container_name: djaman-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: djaman
      MYSQL_USER: user
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: djaman-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
